table Data
	lineageTag: 29d8eb2b-aa6c-45c7-bc55-c76b5793b4dc

	measure 'Avg Speed to Answer' = AVERAGEX('Data', Data[Wait Seconds])
		lineageTag: 78087a67-f65f-4895-a06c-8c26080dbb48

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AVG Speed' =
			
			VAR TotalSeconds = [Avg Speed to Answer]
			VAR Minutes = INT (TotalSeconds / 60)
			VAR Seconds = ROUND(MOD(Totalseconds,60),0)
			RETURN
			FORMAT (Minutes, "0") &":"& FORMAT(Seconds, "00")
		lineageTag: 76a846f2-2d4e-4d05-8f9e-bcf61d5c6232

	measure 'Longest Wait Time' =
			
			VAR TotalSeconds = [Longest Speed to Answer]
			VAR Minutes = INT (TotalSeconds / 60)
			VAR Seconds = ROUND(MOD(Totalseconds,60),0)
			RETURN
			FORMAT (Minutes, "0") &":"& FORMAT(Seconds, "00")
		lineageTag: d4f21a01-57aa-4471-8c07-3df2b8c6844d

	measure 'Longest Speed to Answer' = MAXX('Data', Data[Wait Seconds])
		lineageTag: 301f39b8-642b-4d0e-b1d2-acd36060e035

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg Talk Time' = AVERAGEX('Data', Data[Talk Seconds])
		lineageTag: c48f8611-4cdd-47d1-9a0f-9183a9d2e805

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AVG Talk' =
			
			VAR TotalSeconds = [Avg Talk Time]
			VAR Minutes = INT (TotalSeconds / 60)
			VAR Seconds = ROUND(MOD(Totalseconds,60),0)
			RETURN
			FORMAT (Minutes, "0") &":"& FORMAT(Seconds, "00")
		lineageTag: fd18b651-1378-4e5d-acec-5845f83ceb99

	measure Pct_Under60 = ```
			
			VAR TotalCalls = COUNTROWS(Data)
			VAR CallsUnder60 = CALCULATE(COUNTROWS(Data), 'Data'[Wait Seconds] < 60)
			RETURN
			DIVIDE(CallsUnder60, TotalCalls)
			
			```
		lineageTag: ff497cb0-5651-4299-ae3c-75841f8cb1f8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Donut Value' =
			
			VAR lbl = SELECTEDVALUE ( Slices[Label] )
			RETURN
			SWITCH (
			    TRUE(),
			    lbl = "Filled",     [Pct_Under60],
			    lbl = "Remaining",  1 - [Pct_Under60],
			    BLANK()
			)
		lineageTag: 4be085a3-c505-4289-931b-18f55c55bd0c

	measure 'Donut Color' =
			
			VAR lbl = SELECTEDVALUE ( Slices[Label] )
			RETURN
			IF (
			    lbl = "Remaining",
			    "#E5E5E5",                                 -- light gray
			    SWITCH (
			        TRUE(),
			        [Pct_Under60] >= 0.8, "#107C10",       -- green
			        [Pct_Under60] >= 0.7, "#FFB900",       -- yellow
			        "#E81123"                              -- red
			    )
			)
		lineageTag: 8096893e-0542-4005-87cb-6f8f9f8c87e8

	measure 'Under 60 Seconds' = SUM(talk)
		lineageTag: bff0b47f-5c09-4160-8c38-5f2e50da6a0e

	measure Calls_Under60 = ```
			
			CALCULATE (
			    COUNTROWS ( 'Data' ),
			    'Data'[Wait Seconds] < 60
			)
			
			```
		formatString: 0
		lineageTag: 641dc754-a7e3-4e0c-ae60-98c0da02e47a

	measure Calls_Above60 =
			
			CALCULATE (
			    COUNTROWS ( 'Data' ),
			    'Data'[Wait Seconds] >= 60
			)
		formatString: 0
		lineageTag: e9d0ba6c-75bd-4744-8d57-686754821796

	measure 'Yellow Below 60' = IF(AND([Pct_Under60]<0.8,[Pct_Under60]>=0.6),[Calls_Under60])
		formatString: 0
		lineageTag: 6ffca25b-368f-4ad0-8cf6-52d32fb4e0b7

	measure 'Green Below 60' = IF([Pct_Under60]>=0.8,[Calls_Under60])
		formatString: 0
		lineageTag: 127e1bf1-a5e9-47a6-947f-08c4219d9ffa

	measure 'Red Below 60' = IF([Pct_Under60]<0.6,[Calls_Under60])
		formatString: 0
		lineageTag: a1b52a21-68ec-48cf-836a-8f643d972ba3

	measure 'Row Count' = COUnTROWS(Data)
		formatString: 0
		lineageTag: 054dd849-e464-4785-ba56-5ed986c9343a

	measure 'New New is 3' =
			
			CALCULATE(
			    COUNTROWS('Data'),
			    'Data'[New New Skilled] = "3"
			)
		formatString: 0
		lineageTag: 370a43ea-d767-4f37-a4bc-c2ee7893319a

	measure 'New New is 1' =
			
			CALCULATE(
			    COUNTROWS('Data'),
			    'Data'[New New Skilled] = "1"
			)
		formatString: 0
		lineageTag: 95d9d36f-a84c-41a4-8ed8-248b17183b6d

	measure '%New New is 1' =
			DIVIDE(
			    CALCULATE(
			        COUNTROWS('Data'),
			        'Data'[New New Skilled] = "1"
			    ),
			    COUNTROWS('Data'),
			    0
			)
		formatString: 0
		lineageTag: 80fa36de-55b7-462c-ae39-84a9f29eb535

	measure 'Green New New' = IF([%New New is 1]>=.8,[New New is 1])
		formatString: 0
		lineageTag: 4ea704af-e232-4fba-8cd6-4f1c57195695

	measure 'Yellow New New' = IF(AND([%New New is 1]<0.8,[%New New is 1]>=.7),[New New is 1])
		formatString: 0
		lineageTag: ffadc944-d22a-40d5-81bc-2cb54b6fb327

	measure 'Red New New' = IF([%New New is 1]<.7,[New New is 1])
		formatString: 0
		lineageTag: c981861b-a0c9-4ceb-b7eb-933de4760a2e

	measure '% Abandoned Calls' =
			
			[Abandoned Count]/([Answer Count]+[Abandoned Count])
		lineageTag: 63cf1c93-e414-473e-91e4-9b485ef58df8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Answer Count' =
			
			CALCULATE(
			    COUNTROWS('Data'),
			    'Data'[Call Result] = "Answered"
			)
		formatString: 0
		lineageTag: 3f466d66-5990-4104-8d00-6de4e843fcb6

	measure 'Abandoned Count' =
			
			CALCULATE(
			    COUNTROWS('Data'),
			    'Data'[Call Result] = "Abandoned",
			    'Data'[Under 60] = "0"
			)
		formatString: 0
		lineageTag: ddf8f436-6a4b-405b-9c3f-8dbffaa7d179

	measure 'Green Abdondon' = IF([% Abandoned Calls]<=.04,[Abandoned Count])
		formatString: 0
		lineageTag: 6ff796b3-64bc-47f3-80f1-590a2bbdf4bd

	measure 'Yellow Abdondon' = IF(AND([% Abandoned Calls]>.04,[% Abandoned Calls]<=0.06),[Abandoned Count])
		formatString: 0
		lineageTag: 7db6f092-0114-40c6-81eb-e8a681774d28

	measure 'Red Abdondon' = IF([% Abandoned Calls]>.06,[Abandoned Count])
		formatString: 0
		lineageTag: d3191cd7-c667-4d12-8c5e-18a0bd94156c

	measure 'AVG Wait Time' =
			
			TIME(0, 0, AVERAGE('Data'[Speed of Answer]))
		formatString: General Date
		lineageTag: 0fc4c0b7-0bd6-4834-8b8b-4cf470e230c5

	measure 'AVG Speed to Answer Minutes' = [Avg Speed to Answer]/60
		lineageTag: 084f4c6f-6bef-403d-bcdd-ebb2749f0315

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Longest Speed to Answer Minutes' = MAXX('Data', Data[Wait Seconds])/60
		lineageTag: 006208c6-f3b7-4c92-9ff5-8755f4763f6b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Pasted Date'
		dataType: string
		lineageTag: d9847ef4-0649-412c-b19a-cf17d224eca1
		summarizeBy: none
		sourceColumn: Pasted Date

		annotation SummarizationSetBy = Automatic

	column 'Media Type Name'
		dataType: string
		lineageTag: 1574ca65-9ba1-4f99-89c5-2cc7bee937ee
		summarizeBy: none
		sourceColumn: Media Type Name

		annotation SummarizationSetBy = Automatic

	column ANI/From
		dataType: string
		lineageTag: 43def1b1-7147-48ce-884a-da41afe1c08e
		summarizeBy: none
		sourceColumn: ANI/From

		annotation SummarizationSetBy = Automatic

	column 'Contact ID'
		dataType: string
		lineageTag: 37e03ae4-9d8a-4c57-a469-398d6c89b48a
		summarizeBy: none
		sourceColumn: Contact ID

		annotation SummarizationSetBy = Automatic

	column DNIS/To
		dataType: string
		lineageTag: febf6ff9-eb9d-430c-850b-d000658c559a
		summarizeBy: none
		sourceColumn: DNIS/To

		annotation SummarizationSetBy = Automatic

	column 'Master Contact ID'
		dataType: string
		lineageTag: a1806c54-bd25-441b-b9ea-60906ad96cfd
		summarizeBy: none
		sourceColumn: Master Contact ID

		annotation SummarizationSetBy = Automatic

	column 'Contact Agent Name'
		dataType: string
		lineageTag: d578232d-3e68-4bcb-9ec1-99697041bf41
		summarizeBy: none
		sourceColumn: Contact Agent Name

		annotation SummarizationSetBy = Automatic

	column 'Contact Skill Name'
		dataType: string
		lineageTag: a162ebf2-8e36-4322-ac96-5eaeb5c6d9fc
		summarizeBy: none
		sourceColumn: Contact Skill Name

		annotation SummarizationSetBy = Automatic

	column 'Contact Start Date Time'
		dataType: dateTime
		formatString: General Date
		lineageTag: 1ca067d0-caee-4556-8b3f-dfc92f2929d4
		summarizeBy: none
		sourceColumn: Contact Start Date Time

		variation Variation
			isDefault
			relationship: 87e02dc9-1077-4f2c-a9a8-b3a8117d256a
			defaultHierarchy: LocalDateTable_c70fa812-e64a-4b9b-a03b-83ebdc8f96b3.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Contact End Date Time'
		dataType: dateTime
		formatString: General Date
		lineageTag: b716ec13-221d-43d2-a9b1-d16b0852abf9
		summarizeBy: none
		sourceColumn: Contact End Date Time

		variation Variation
			isDefault
			relationship: a06ed5c4-07f8-4e2f-a0b8-ed61d6e25a34
			defaultHierarchy: LocalDateTable_f86e0275-dd38-4f90-972e-cd6e0367f964.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Prequeued
		dataType: string
		lineageTag: cb9dacec-2e88-475a-b073-b575b914a8cd
		summarizeBy: none
		sourceColumn: Prequeued

		annotation SummarizationSetBy = Automatic

	column 'Prequeue Time'
		dataType: string
		lineageTag: fe471cdb-3822-439b-b1e8-c788e75c1350
		summarizeBy: none
		sourceColumn: Prequeue Time

		annotation SummarizationSetBy = Automatic

	column 'Prequeue Abandons'
		dataType: string
		lineageTag: b194dd40-657d-458e-9304-1f20fe70dbe2
		summarizeBy: none
		sourceColumn: Prequeue Abandons

		annotation SummarizationSetBy = Automatic

	column 'Inqueue Time'
		dataType: string
		lineageTag: a8d4723b-b78e-4353-8ebb-dd39212f3dad
		summarizeBy: none
		sourceColumn: Inqueue Time

		annotation SummarizationSetBy = Automatic

	column 'Talk Time'
		dataType: string
		lineageTag: 2666f946-427a-4bc3-a966-35371f6caeee
		summarizeBy: none
		sourceColumn: Talk Time

		annotation SummarizationSetBy = Automatic

	column 'ACW Time'
		dataType: string
		lineageTag: befcc2c4-5be7-4ee0-a41e-d91c0233fea6
		summarizeBy: none
		sourceColumn: ACW Time

		annotation SummarizationSetBy = Automatic

	column 'Postqueue Time'
		dataType: string
		lineageTag: 9d71a41f-bc00-4ce4-b095-1a1d4dffde00
		summarizeBy: none
		sourceColumn: Postqueue Time

		annotation SummarizationSetBy = Automatic

	column 'Abandon Time'
		dataType: string
		lineageTag: 113da68e-5ad5-410b-a6a9-35ab3f1bdeb1
		summarizeBy: none
		sourceColumn: Abandon Time

		annotation SummarizationSetBy = Automatic

	column Abandons
		dataType: string
		lineageTag: 697584fd-8f69-4361-b699-40c6b3f77633
		summarizeBy: none
		sourceColumn: Abandons

		annotation SummarizationSetBy = Automatic

	column 'Contact Duration'
		dataType: string
		lineageTag: df9c3cc2-92fb-4625-a6bd-6cd2ec68e53e
		summarizeBy: none
		sourceColumn: Contact Duration

		annotation SummarizationSetBy = Automatic

	column 'Speed Of Answer Pasted'
		dataType: string
		lineageTag: c4d83356-3ef9-4628-af26-329248966fd6
		summarizeBy: none
		sourceColumn: Speed Of Answer Pasted

		annotation SummarizationSetBy = Automatic

	column 'Wait Seconds' = (Data[Speed of Answer]-1)*86400
		dataType: double
		lineageTag: 481b8161-159b-49a8-9fc5-61115821ca48
		summarizeBy: sum

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Talk Seconds' = HOUR(Data[Talk Time]) * 3600 + MINUTE(Data[Talk Time]) * 60 + SECOND(Data[Talk Time])
		lineageTag: cd8b49a5-0aae-4da4-ad21-b5b8c17b353e
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Hour Sort Order' =
			
			IF(VALUE('Data'[Hour1]) >= 5, VALUE('Data'[Hour1]) - 5, VALUE('Data'[Hour1]) + 19)
		lineageTag: d3136285-0162-416b-b8d8-651e276b3d8c
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Abv Day of Week' = FORMAT('Data'[Reporting Date], "ddd")
		lineageTag: e2e9bf4a-cace-4e91-b90a-d067ecf3ca97
		summarizeBy: none
		sortByColumn: 'Abv Day Sort'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Abv Day Sort' = WEEKDAY('Data'[Reporting Date], 2)
		formatString: 0
		lineageTag: 463116d3-9043-41ff-9d7b-ad5c69628539
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Conatins ROQ?' =
			
			IF(
			    CONTAINSSTRING(Data[Contact Skill Name], "ROQ"),
			    "Y",
			    "N"
			)
		lineageTag: fcd9dc83-cf32-4a0f-9668-3c02f31ef290
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Team Sort Order'
		dataType: int64
		formatString: 0
		lineageTag: 9c2c0c96-2096-42b0-ac5d-c3ccc4145be3
		summarizeBy: sum
		sourceColumn: Team Sort Order

		annotation SummarizationSetBy = Automatic

	column 'Hour Nights Sort'
		dataType: int64
		formatString: 0
		lineageTag: ee1792bf-b122-4f68-8bf4-f24791f64b49
		summarizeBy: sum
		sourceColumn: Hour Nights Sort

		annotation SummarizationSetBy = Automatic

	column PeriodFlag =
			
			VAR CurrentDate = Data[Reporting Date]
			VAR TodayDate = TODAY()
			VAR ThisWeekStart = TodayDate - WEEKDAY(TodayDate, 2) + 1
			VAR ThisWeekEnd = ThisWeekStart + 6
			VAR LastFriday = TodayDate - WEEKDAY(TodayDate, 2) - 2
			VAR LastSunday = LastFriday + 2
			VAR LastWeekStart = ThisWeekStart - 7
			VAR LastWeekEnd = ThisWeekStart - 1
			
			RETURN
			    SWITCH(
			        TRUE(),
			        CurrentDate >= ThisWeekStart && CurrentDate <= ThisWeekEnd, "This Week",
			        CurrentDate >= LastFriday && CurrentDate <= LastSunday, "Last Fri-Sun",
			        CurrentDate >= LastWeekStart && CurrentDate <= LastWeekEnd, "Last Week",
			        CurrentDate >= DATE(YEAR(TodayDate), MONTH(TodayDate), 1) && CurrentDate <= EOMONTH(TodayDate, 0), "This Month",
			        CurrentDate >= DATE(YEAR(EOMONTH(TodayDate, -1)), MONTH(EOMONTH(TodayDate, -1)), 1) && CurrentDate <= EOMONTH(TodayDate, -1), "Last Month",
			        CurrentDate >= DATE(YEAR(TodayDate), (QUARTER(TodayDate) - 1) * 3 + 1, 1) && CurrentDate <= EOMONTH(DATE(YEAR(TodayDate), (QUARTER(TodayDate) - 1) * 3 + 1, 1), 2), "This Quarter",
			        CurrentDate >= DATE(YEAR(EOMONTH(TodayDate, -3)), MONTH(EOMONTH(TodayDate, -3)) - 2, 1) && CurrentDate <= EOMONTH(TodayDate, -3), "Last Quarter",
			        CurrentDate >= DATE(YEAR(TodayDate), 1, 1) && CurrentDate <= DATE(YEAR(TodayDate), 12, 31), "This Year",
			        CurrentDate >= DATE(YEAR(TodayDate) - 1, 1, 1) && CurrentDate <= DATE(YEAR(TodayDate) - 1, 12, 31), "Last Year",
			        BLANK()
			    )
		lineageTag: 0cf6b377-8120-4d1f-98ba-dca3d0ae97ef
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Day - Hour' = 'Data'[Day of Week] & " - " & FORMAT('Data'[Hour], "0")
		lineageTag: cc240a0f-4e03-4887-bbd4-cf32d73aa359
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Time of Day Sort' =
			
			VAR dt = 'Data'[Contact Start Date Time]
			VAR h = HOUR(dt)
			VAR m = MINUTE(dt)
			VAR RoundedMin = FLOOR(m, 15)
			VAR SlotInDay = h * 4 + RoundedMin / 15
			VAR AdjustedSlot = MOD(SlotInDay - 20, 96) + 1
			RETURN
			    AdjustedSlot
		lineageTag: 271f930d-4e52-4eab-bc10-a6beb5efb21d
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Call Result'
		dataType: string
		lineageTag: 21f50863-bf48-422a-a51f-34b1fb2f7572
		summarizeBy: none
		sourceColumn: Call Result

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 2f376d72-088d-4767-a430-667c84614f2f
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: 5f12166f-3e2b-4b04-b4e1-15d33ea448e0
			defaultHierarchy: LocalDateTable_bcac9e68-85df-4a6e-9c21-384df1bf2533.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Time
		dataType: dateTime
		formatString: Long Time
		lineageTag: c547897b-cdeb-4776-afb7-e8f2001c5dcd
		summarizeBy: none
		sourceColumn: Time

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column Hour1
		dataType: int64
		formatString: 0
		lineageTag: 9b5bffee-88d0-42c5-bcd8-709af500bdef
		summarizeBy: sum
		sourceColumn: Hour1

		annotation SummarizationSetBy = Automatic

	column Hour
		dataType: string
		lineageTag: 21a297ab-557a-4785-9b42-2984d80e434b
		summarizeBy: none
		sourceColumn: Hour
		sortByColumn: 'Hour Sort Order'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Minute
		dataType: int64
		formatString: 0
		lineageTag: 40d1fc1c-537d-499e-a0cc-0f5d9f816816
		summarizeBy: sum
		sourceColumn: Minute

		annotation SummarizationSetBy = Automatic

	column 'Speed of Answer'
		dataType: dateTime
		formatString: h:nn
		lineageTag: ff286f3a-798f-4dce-a792-c904ea10f6df
		summarizeBy: none
		sourceColumn: Speed of Answer

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Under 60'
		dataType: string
		lineageTag: 61dbf90b-0146-4cc6-8582-983fb1a8d96b
		summarizeBy: none
		sourceColumn: Under 60

		annotation SummarizationSetBy = Automatic

	column 'Reporting Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 0f606553-baa7-4a3c-a444-4901da3982a0
		summarizeBy: none
		sourceColumn: Reporting Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Month
		dataType: int64
		formatString: 0
		lineageTag: 963b19ad-55ab-483c-8db9-36bef938d34a
		summarizeBy: sum
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column 'New New Skilled'
		dataType: string
		lineageTag: 2c1b1f08-3a10-4794-8cc5-7e938500b4b2
		summarizeBy: none
		sourceColumn: New New Skilled

		annotation SummarizationSetBy = Automatic

	column 'Day of Week'
		dataType: string
		lineageTag: 8f198ae8-75f9-4d04-a3e9-06718999a707
		summarizeBy: none
		sourceColumn: Day of Week

		annotation SummarizationSetBy = Automatic

	column 'Customer Name'
		dataType: string
		lineageTag: 8037cb43-a60d-475c-8440-63018fcd1c22
		summarizeBy: none
		sourceColumn: Customer Name

		annotation SummarizationSetBy = Automatic

	column Program
		dataType: string
		lineageTag: 8d8cd283-3c74-4929-898f-9e84389971b4
		summarizeBy: none
		sourceColumn: Program

		annotation SummarizationSetBy = Automatic

	column 'Service Line'
		dataType: string
		lineageTag: 8209aa14-76e2-436a-9987-ecbfd430d1d0
		summarizeBy: none
		sourceColumn: Service Line

		annotation SummarizationSetBy = Automatic

	column Skilled
		dataType: string
		lineageTag: b39405e6-1925-4586-b078-6eda07c5e77c
		summarizeBy: none
		sourceColumn: Skilled

		annotation SummarizationSetBy = Automatic

	column 'New Skilled'
		dataType: string
		lineageTag: 3f27ff41-0e27-4651-b063-ac3cde1f7360
		summarizeBy: none
		sourceColumn: New Skilled

		annotation SummarizationSetBy = Automatic

	column Team
		dataType: string
		lineageTag: d4f62980-0614-4087-8ede-fa5fca2e740c
		summarizeBy: none
		sourceColumn: Team
		sortByColumn: 'Team Sort Order'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Hour Nights'
		dataType: string
		lineageTag: 62241de0-7722-4dbe-b388-7434e7cd5f30
		summarizeBy: none
		sourceColumn: Hour Nights
		sortByColumn: 'Hour Nights Sort'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Reporting Day'
		dataType: string
		lineageTag: 4f70b24b-766a-4758-a23b-719716e47a82
		summarizeBy: none
		sourceColumn: Reporting Day

		annotation SummarizationSetBy = Automatic

	column 'Time of Day' =
			
			VAR dt = 'Data'[Contact Start Date Time]
			VAR h = HOUR(dt)
			VAR m = MINUTE(dt)
			VAR RoundedMin = FLOOR(m, 15)
			VAR h12 = IF(MOD(h, 12) = 0, 12, MOD(h, 12))
			VAR ampm = IF(h < 12, "a", "p")
			VAR minText = IF(RoundedMin = 0, ":00", ":" & FORMAT(RoundedMin, "00"))
			RETURN
			    h12 & minText & ampm
		lineageTag: 540d09d2-ae31-4fea-b487-b0146a2fe1cb
		summarizeBy: none
		sortByColumn: 'Time of Day Sort'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	hierarchy 'Hour Hierarchy'
		lineageTag: 29292e15-38ec-474a-82ce-fcb7c44867bb

		level Hour
			lineageTag: fe3387b4-2fe8-4ea9-b90a-06560aac8324
			column: Hour

		level 'Time of Day'
			lineageTag: 86e87407-1e3f-4f4e-8e9b-b18a3d14ba11
			column: 'Time of Day'

	partition Data = m
		mode: import
		source = ```
				let
				    // Append all monthly queries
				    Source = Table.Combine({
				        #"12012025",
				        #"11012025",
				        #"10012025",
				        #"09012025",
				        #"06012025",
				        #"03012025"
				    }),
				    
				    // Do ALL type conversions upfront
				    #"Changed Type" = Table.TransformColumnTypes(Source,{
				        {"Contact Start Date Time", type datetime}, 
				        {"Contact End Date Time", type datetime}
				    }),
				    
				    // Remove old columns early
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{
				        "Call Result", "Date", "Day of Week", "Time", "Hour1", "Hour", "Minute", 
				        "Under 60", "Skilled", "Customer Name", "Program", "Reporting Date", 
				        "Reporting Day", "Service Line", "Speed of Answer", "Talk Time", "ACW Time", 
				        "Contact Duration", "Month", "New Skilled", "New New Skilled", "Team", 
				        "Minute Bucket", "Combo", "Adressable", "Weekday"
				    }),
				    
				    // Buffer lookup tables for performance
				    BufferedCustomer = Table.Buffer(Table.Distinct(Customer, {"Reference"})),
				    BufferedNurse = Table.Buffer(Table.Distinct(#"Nurse Reference", {"Log in Reference", "Client"})),
				    BufferedTeam = Table.Buffer(Table.Distinct(Team, {"Day of Week", "Hour", "Customer Name"})),
				    
				    // Add all calculated columns BEFORE merges
				    #"Added Date" = Table.AddColumn(#"Removed Columns", "Date", each Date.From([Contact Start Date Time]), type date),
				    
				    #"Added Day of Week" = Table.AddColumn(#"Added Date", "Day of Week", each 
				        try Date.ToText(Date.From([Pasted Date]), "ddd") otherwise null,
				    type text),
				    
				    #"Added Time" = Table.AddColumn(#"Added Day of Week", "Time", each Time.From([Contact Start Date Time]), type time),
				    
				    #"Added Hour1" = Table.AddColumn(#"Added Time", "Hour1", each Time.Hour([Contact Start Date Time]), Int64.Type),
				    
				    #"Added Hour" = Table.AddColumn(#"Added Hour1", "Hour", each 
				        let h = [Hour1]
				        in if h = 0 then "12 AM"
				           else if h = 12 then "12 PM"
				           else if h < 12 then Text.From(h) & " AM"
				           else Text.From(h - 12) & " PM",
				    type text),
				    
				    #"Added Minute" = Table.AddColumn(#"Added Hour", "Minute", each Time.Minute([Contact Start Date Time]), Int64.Type),
				    
				    #"Added Reporting Date" = Table.AddColumn(#"Added Minute", "Reporting Date", each 
				        if [Hour1] < 5 then Date.AddDays([Date], -1) else [Date],
				    type date),
				    
				    #"Added Month" = Table.AddColumn(#"Added Reporting Date", "Month", each Date.Month([Reporting Date]), Int64.Type),
				    
				    // Rename pasted columns
				    #"Renamed Pasted Columns" = Table.RenameColumns(#"Added Month",{
				        {"Talk Time Pasted", "Talk Time"}, 
				        {"ACW Time Pasted", "ACW Time"}, 
				        {"Contact Duration Pasted", "Contact Duration"}
				    }),
				    
				    // Add Call Result
				    #"Added Call Result" = Table.AddColumn(#"Renamed Pasted Columns", "Call Result", each 
				        let
				            skill = try [Contact Skill Name] otherwise "",
				            abandons = try [Abandons] otherwise null,
				            prequeue = try [Prequeue Abandons] otherwise null,
				            talkTime = try [Talk Time] otherwise null,
				            hasAbandons = if abandons = null then false else abandons > 0,
				            hasPrequeue = if prequeue = null then false else prequeue > 0,
				            hasTalkTime = if talkTime = null then false else try Text.Length(Text.From(talkTime)) > 0 otherwise false
				        in
				            if skill = "Manual Outbound" then "Outbound"
				            else if hasAbandons or hasPrequeue then "Abandoned"
				            else if hasTalkTime then "Answered"
				            else null,
				    type text),
				    
				    // Add Speed of Answer
				    #"Added Speed of Answer" = Table.AddColumn(#"Added Call Result", "Speed of Answer", each let
				    callResult = [Call Result],
				    speedPasted = try [Speed Of Answer Pasted] otherwise "",
				    durationPasted = try [Contact Duration] otherwise "",
				    durationValue = if callResult = "Answered" then try Duration.From(speedPasted) otherwise null
				                    else if callResult = "Abandoned" or callResult = "Outbound" then try Duration.From(durationPasted) otherwise null
				                    else null
				in
				    if durationValue = null then null
				    else #datetime(1899, 12, 31, 0, 0, 0) + durationValue),
				    
				    // Add Under 60
				    #"Added Under 60" = Table.AddColumn(#"Added Speed of Answer", "Under 60", each let
				    speed = try [Speed of Answer] otherwise null,
				    baseDateTime = #datetime(1899, 12, 31, 0, 0, 0),
				    oneMinuteDateTime = #datetime(1899, 12, 31, 0, 1, 0)
				in
				    if speed = null then null
				    else if speed < oneMinuteDateTime then 1
				    else 0),
				    
				    // NOW do the merges - all at once
				    #"Merged Customer" = Table.NestedJoin(#"Added Under 60", {"Contact Skill Name"}, BufferedCustomer, {"Reference"}, "Customer", JoinKind.LeftOuter),
				    #"Expanded Customer" = Table.ExpandTableColumn(#"Merged Customer", "Customer", {"Customer", "Program", "Service Line", "Skilled"}, {"Customer", "Program", "Service Line", "Skilled"}),
				    
				    #"Merged Nurse" = Table.NestedJoin(#"Expanded Customer", {"Contact Agent Name", "Customer"}, BufferedNurse, {"Log in Reference", "Client"}, "Nurse Reference", JoinKind.LeftOuter),
				    #"Expanded Nurse" = Table.ExpandTableColumn(#"Merged Nurse", "Nurse Reference", {"Skill Reference"}, {"New Skilled"}),
				    
				    // Add New New Skilled
				    #"Added New New Skilled" = Table.AddColumn(#"Expanded Nurse", "New New Skilled", each 
				        try (
				            if [Skilled] = false then 1
				            else if [Skilled] = "ELSE" then 2
				            else if [Skilled] = true and [New Skilled] = 1 then 1
				            else 3
				        ) otherwise 3,
				    Int64.Type),
				    
				    #"Merged Team" = Table.NestedJoin(#"Added New New Skilled", {"Day of Week", "Hour1", "Customer"}, Team, {"Day of Week", "Hour", "Customer Name"}, "Team", JoinKind.LeftOuter),
				    #"Expanded Team" = Table.ExpandTableColumn(#"Merged Team", "Team", {"Team"}, {"Team"}),
				    
				    // Add sorting columns
				    #"Added Team Sort" = Table.AddColumn(#"Expanded Team", "Team Sort Order", each 
				        let t = [Team]
				        in
				            // Standard Teams
				            if t = "Team 1" then 1
				            else if t = "Team 2" then 2
				            else if t = "Team 3" then 3
				            else if t = "Team 4" then 4
				            else if t = "Team 5" then 5
				            else if t = "Team 6" then 6
				            else if t = "Team 7" then 7
				            else if t = "Team 8" then 8
				            else if t = "Team 9" then 9
				            else if t = "Team 10" then 10
				            else if t = "Team 11" then 11
				            else if t = "Team 12" then 12
				            // NAL Weekend Teams
				            else if t = "NAL Weekend Morning" then 20
				            else if t = "NAL Weekend Day" then 21
				            else if t = "NAL Weekend Evening" then 22
				            else if t = "NAL Weekend Overnight" then 23
				            // WED## Teams
				            else if t = "WED1" then 101
				            else if t = "WED2" then 102
				            else if t = "WED3" then 103
				            else if t = "WED4" then 104
				            else if t = "WED5" then 105
				            else if t = "WED6" then 106
				            else if t = "WED7" then 107
				            else if t = "WED8" then 108
				            else if t = "WED9" then 109
				            else if t = "WED10" then 110
				            else if t = "WED11" then 111
				            else if t = "WED12" then 112
				            // WEM## Teams
				            else if t = "WEM1" then 121
				            else if t = "WEM2" then 122
				            else if t = "WEM3" then 123
				            else if t = "WEM4" then 124
				            else if t = "WEM5" then 125
				            else if t = "WEM6" then 126
				            else if t = "WEM7" then 127
				            else if t = "WEM8" then 128
				            else if t = "WEM9" then 129
				            else if t = "WEM10" then 130
				            else if t = "WEM11" then 131
				            else if t = "WEM12" then 132
				            // WEE## Teams
				            else if t = "WEE1" then 141
				            else if t = "WEE2" then 142
				            else if t = "WEE3" then 143
				            else if t = "WEE4" then 144
				            else if t = "WEE5" then 145
				            else if t = "WEE6" then 146
				            else if t = "WEE7" then 147
				            else if t = "WEE8" then 148
				            else if t = "WEE9" then 149
				            else if t = "WEE10" then 150
				            else if t = "WEE11" then 151
				            else if t = "WEE12" then 152
				            else 999,
				    Int64.Type),
				    
				    #"Added Hour Nights" = Table.AddColumn(#"Added Team Sort", "Hour Nights", each [Hour], type text),
				    
				    #"Added Hour Nights Sort" = Table.AddColumn(#"Added Hour Nights", "Hour Nights Sort", each 
				        let h = [Hour Nights]
				        in
				            if h = "11 PM" then 1
				            else if h = "12 AM" then 2
				            else if h = "1 AM" then 3
				            else if h = "2 AM" then 4
				            else if h = "3 AM" then 5
				            else if h = "4 AM" then 6
				            else if h = "5 AM" then 7
				            else if h = "6 AM" then 8
				            else if h = "7 AM" then 9
				            else 999,
				    Int64.Type),
				    #"Added Custom" = Table.AddColumn(#"Added Hour Nights Sort", "Reporting Day", each try Date.DayOfWeek([Reporting Date], Day.Sunday) + 1 otherwise null),
				    #"Renamed Columns" = Table.RenameColumns(#"Added Custom",{{"Customer", "Customer Name"}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Renamed Columns",{{"New New Skilled", type text}})
				in
				    #"Changed Type1"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

